services:
  server:
    image: go-server
    restart: always
    build: 
      context: .
      args:
        MODE: debug
    ports:
      - "4200:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"